import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@components/Header";
import HomeBanner from "@components/Home/HomeBanner";
import HomePromoProducts from "@components/Home/HomePromoProducts";

export default function Home() {
  return (
    <>
      <Head>
        <title>LUD - Leather Goods</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main>
        <Header />
        <HomeBanner />
        <HomePromoProducts />
      </main>
    </>
  );
}
